apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-deployment
  namespace: #{KUBE_NAMESPACE}#
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: webapi
  template:
    metadata:
      labels:
        bb: webapi
    spec:
      containers:
      - name: webapi-container
        image: 10.3.20.208:5000/WEP-API:#{Release.Artifacts.artifacts.BuildId}#
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: #{ASPNETCORE_ENVIRONMENT}#
---
apiVersion: v1
kind: Service
metadata:
  name: webapi-service
  namespace: #{KUBE_NAMESPACE}#
spec:
  type: NodePort
  selector:
    bb: webapi
  ports:
  - port: 80
    targetPort: 80
    nodePort: #{EXPOSED_PORT}#
